apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    app: karsajobs-frontend
    # tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 31944
  selector:
    app: karsajobs-frontend
    # tier: frontend
