apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    app: karsajobs
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 31943
  selector:
    tier: backend
