apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  # labels:
  #   app: mongo
spec:
  ports:
  - port: 27017
    # protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
    # tier: mongodb
  # clusterIP: None
